#!/usr/bin/env bash

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  
  umask 022

  local many="${1:-10}"
  
  git pull
  block lock sync
  home status
}

source sub "$BASH_SOURCE" "$@"
