#!/usr/bin/env bash

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source normalize

  local nm_host="$(hostname -s)"
  if [[ -f "$shome/.host-name" ]]; then
    nm_host="$(cat "$shome/.host-name")"
  fi

  local nm_user="$(id -un)"

  cd "$shome/.ssh"
  ssh-add "git-${nm_user}@${nm_host}" "ssh-${nm_user}@${nm_host}"

}

source sub "$BASH_SOURCE" "$@"
