#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  set -x

  "$@" rm -rf home .git
  cat <<EOF | "$@" tee -a .ssh/config

Host github.com
  StrictHostKeyChecking no
  ForwardAgent no

EOF
  "$@" git clone "${HOME_REPO:-$(git remote get-url origin)}" home
  "$@" mv home/.git .
  "$@" rm -rf home .profile .bashrc .bash_profile Blockfile.json.site # TODO DRY block-gen-cibuild
  "$@" git reset --hard

  home remote "$@"
}

source sub "$BASH_SOURCE" "$@"
