#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local many="${1:-10}"
  
  export GIT_SSH="$(type -P cache-git)"
  block runmany "$many" 'cd $1 && git pull'
}

source sub "$BASH_SOURCE" "$@"
