#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  
  umask 022

  local many="${1:-10}"
  
  block runmany "$many" 'cd $1 && git pull' || true
  block clone
  block runmany "$many" 'cd $1 && gs' || sort | talign 3
}

source sub "$BASH_SOURCE" "$@"
