#!/usr/bin/env bash

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source normalize  

  "$@" -A git pull
  "$@" -A home update
  home remote "$@"
}

source sub "$BASH_SOURCE" "$@"
