#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  
  cd "$shome"
  block lock
  git diff
  git add Blockfile.json
  git commit -v
}

source sub "$BASH_SOURCE" "$@"
