#!/usr/bin/env bash

function home_package {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

  export PKG_HOME="$shome"
  export APP_PATH="$shome/work"
}

home_package
