#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  local many="${1:-10}"
  
  git pull
  block lock sync
  home status
}

source sub "$BASH_SOURCE" "$@"
