#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  set -x

  "$@" env http_proxy=$http_proxy https_proxy=$https_proxy ssh_gateway=$ssh_gateway ssh_gateway_user=$LOGNAME script/cibuild '~'
  "$@" block compile service
}

source sub "$BASH_SOURCE" "$@"
