#!/usr/bin/env bash

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source normalize  

  set -x

  if ! "$@" test -d .git; then
    "$@" ssh -o StrictHostKeyChecking=no github.com true || true
    "$@" -A git clone git@github.com:defn/home 
    "$@" mv home/.git .
    "$@" git reset --hard
    "$@" rm -rf home .profile
  fi

  "$@" -A env http_proxy=$http_proxy https_proxy=$https_proxy ssh_gateway=$ssh_gateway ssh_gateway_user=$LOGNAME script/cibuild '~'
  "$@" rm -rf .profile home
  "$@" block compile service
  "$@" pkg ensure misc/screen
}

source sub "$BASH_SOURCE" "$@"
