#!/usr/bin/env bash

function setBackground {
  local clr="$1"; shift
  case "$TERM_PROGRAM" in
    iTerm.app)
      echo -e "\033]Ph${clr}\033\\"
      ;;
  esac
}

function vim {
  local clr_vim="c1c1c1"
  local clr_bg="c1c1c1"
  if [[ "${ITERM_PROFILE:-}" == "slight" ]]; then
    clr_bg="ffffd7"
  fi

  ( setBackground "$clr_vim" & )
  ( exec vim "$@" )
  ( setBackground "$clr_bg" & )
}

