#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  local many="${1:-10}"
  
  block runmany "$many" 'unset GIT_SSH; cd $1 && git fetch --all'
}

source sub "$BASH_SOURCE" "$@"
