#!/usr/bin/env bash

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  
  block lock
  git add Blockfile.lock
  git diff --cached
  git commit -v
}

source sub "$BASH_SOURCE" "$@"
