#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  set -x

  "$@" git pull
  "$@" home update

  home remote "$@"
}

source sub "$BASH_SOURCE" "$@"
