#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize

  if [[ -f "$shome/.ssh-agent" ]]; then
    source "$shome/.ssh-agent"
    if ! ssh-add -l >/dev/null 2>&1; then
      case "$?" in
        1)
          true
          ;;
        *)
          rm -f "$shome/.ssh-agent"
          ;;
      esac
    fi
  fi

  if [[ ! -f "$shome/.ssh-agent" ]]; then
    ssh-agent > "$shome/.ssh-agent"
  fi

  if ! ssh-add -l >/dev/null 2>&1; then
    case "$?" in
      1)
         home ssh add
        ;;
    esac
  fi
}

source sub "$BASH_SOURCE" "$@"
