#!/usr/bin/env bash

function setBackground {
  local clr="$1"; shift

  case "$TERM_PROGRAM" in
    iTerm.app)
      echo -e "\033]Ph${clr}\033\\"
      ;;
  esac
}

function vim {
  local clr_bg="1c1c1c"
  if [[ "${CUE_SCHEME:-}" == "slight" ]]; then
    clr_bg="ffffd7"
  fi

  if [[ "$TERM_PROGRAM" == "Apple_Terminal" ]]; then
    export CUE_SCHEME_VIM='sdark'
  else
    export CUE_SCHEME_VIM="$CUE_SCHEME"
  fi

  setBackground "$clr_bg"
  command vim "$@"
  snormal
}

function vi {
  vim "$@"
}
