#!/usr/bin/env bash

umask 022

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  set -x

  if [[ -f "$shome/ssh-agent" ]]; then
    source "$shome/ssh-agent"
    if ! ssh-add -l >/dev/null 2>&1; then
      case "$?" in
        1)
          true
          ;;
        *)
          rm -f "$shome/ssh-agent"
          ;;
      esac
    fi
  fi

  if [[ ! -f "$shome/ssh-agent" ]]; then
    ssh-agent > "$shome/.ssh-agent"
  fi

  home ssh add
}

source sub "$BASH_SOURCE" "$@"
