#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  set -x

  "$@" ssh -o StrictHostKeyChecking=no github.com true || true
  "$@" -A git clone git@github.com:defn/home
  "$@" mv home/.git .
  "$@" git reset --hard
  "$@" rm -rf home .profile

  home remote "$@"
}

source sub "$BASH_SOURCE" "$@"
