#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local many="${1:-10}"
  
  umask 022

  app runmany "$many" 'cd $1 && git pull && git push' || true
  app runmany "$many" 'echo $1 $(cd $1 && gs)' | talign 3
}

source sub "$BASH_SOURCE" "$@"
