#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  set -x

  "$@" rm -rf home .git
  cat <<EOF | "$@" tee -a .ssh/config

Host github.com
  StrictHostKeyChecking no
  ForwardAgent no

EOF
  "$@" git clone "${HOME_REPO:-git@github.com:defn/home}" home
  "$@" mv home/.git .
  "$@" git reset --hard
  "$@" rm -rf home .profile

  home remote "$@"
}

source sub "$BASH_SOURCE" "$@"
