#!/usr/bin/env bash

umask 022

function main {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  cd "$shome"

  block list | { 
    echo '<tt>'
    while read -r name dir git meh; do 
      echo "$name" 1>&2
      echo "$name"
      echo "<a href='$git'>git</a>"
      if [[ -f $dir/gh-pages/index.html ]]; then
        echo "<a href='$name'>docs</a>"
      fi
      echo "<br/>"
    done
    echo '</tt>'
  } > $BLOCK_PATH/defn.github.io/index.html
}

source sub "$BASH_SOURCE" "$@"
