#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source normalize  

  local many="${1:-10}"
  
  unset GIT_SSH

  cache git update
  block runmany "$many" 'unset GIT_SSH; cd $1 && cache pull' || true
  block clone
  block lock
  home status
}

source sub "$BASH_SOURCE" "$@"
