#!/usr/bin/env bash

function home_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  local fl_first=
  local cmd_app="$(which app 2>&- || true)"
  if [[ ! -x "$cmd_app" ]]; then
    if [[ ! -d "$shome/work/app" ]]; then
      git clone git@github.com:defn/app "$shome/work/app"
      (cd "$shome/work/app" && script/bootstrap)
      fl_first=1
    fi
  fi

  if [[ -n "$fl_first" ]]; then
    for a in sub app jq pkgsrc python ansible aws gcloud erlang elixir \
             phoenix ruby rocco tugboat node dnsimple cue junas defn runmany deploy context \
             virtualbox packer vagrant basebox boxcar basebox basebox-vagrants leiningen \
             browserify-gulp-example; do
      git clone git@github.com:defn/app-$a work/$a || git clone git@github.com:defn/$a work/$a || true
      (cd work/$a && git pull)
    done
  fi

  "$shome/script/update"
  source "$shome/script/profile"

  if [[ ! -x "$(which bmake 2>&- || true)" ]]; then
    pkg install bootstrap
  fi

  if [[ -x "$(which pkg 2>&- || true)" ]]; then
    pkg install security/mozilla-rootcerts
    mozilla-rootcerts install || true

    pkg install security/spiped
    pkg install misc/getopt
    pkg install misc/tmux
    pkg install net/wget www/curl
    pkg install devel/jq
    pkg install www/squid
    pkg install devel/editline misc/rlwrap
    pkg install sysutils/runit
    pkg install www/nginx
    pkg install databases/redis
    pkg install databases/postgresql94-server
    pkg install databases/mysql-server databases/percona-toolkit
    pkg install databases/mongodb
  fi
}

home_bootstrap "$@"
