#!/usr/bin/env bash

function work_bootstrap {
  runmany 'set -x; cd $1 && app bootstrap' "$@"
}

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  cd "$shome"

  git submodule update --init --recursive

  source "$shome/work/app/script/profile"
  cd "$shome/work"
  require runmany

  work_bootstrap junas jq
  work_bootstrap node dnsimple
  work_bootstrap erlang elixir
  work_bootstrap python ansible aws gcloud letsencrypt
  work_bootstrap ruby rocco tugboat
  work_bootstrap go hub

  require
}

bootstrap
