#!/usr/bin/env bash

function work_bootstrap {
  local nm_app
  for nm_app in "$@"; do
    pushd "$APP_PATH/$1" >/dev/null
    bootstrap
    popd >/dev/null
  done
}

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  cd "$shome"

  export APP_PATH="$shome/work"

  #git submodule update --init --recursive

  source "$APP_PATH/app/script/profile"
  #app compile gitsubmodule
  app compile definitions

  require
}

bootstrap
