#!/usr/bin/env bash

function home_update {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  source "$shome/work/app/script/profile"
  require

  pushd "$shome/work/pkgsrc" && source script/profile && script/bootstrap && popd

  if [[ ! -x "$(which bmake 2>&- || true)" ]]; then
    pkg package bootstrap
  fi

  if [[ -x "$(which pkg 2>&- || true)" ]]; then
    pkg package security/mozilla-rootcerts
    pkg package security/spiped
    pkg package misc/getopt
    pkg package misc/tmux
    pkg package net/wget www/curl
    pkg package devel/jq
    env CFLAGS=-O2 pkg package www/squid3 
    pkg package devel/editline misc/rlwrap
    pkg package sysutils/runit
    pkg package sysutils/cdrtools
    pkg package www/nginx
    pkg package databases/redis
    pkg package databases/postgresql94-server
    pkg package databases/mysql55-server databases/percona-toolkit
    pkg package databases/mongodb
    pkg package lang/erlang
  fi
}

home_update "$@"
