#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  
  case "${1:-}" in
    pkgsrc)
      ${WRKOBJDIR:+rm -rf "$WRKOBJDIR"}
      ;;
    *)
      rm -vf "$shome/.bashrc.app" "$shome/Blockfile.txt"
      ;;
  esac
}

main "$@"
