#!/usr/bin/env bash

function main {
  local shome="${_github_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if type -P jupyter-console >/dev/null; then
    return 0
  fi

  if type -P tree >/dev/null; then
    return 0
  fi

  if type -P uuidgen >/dev/null; then
    return 0
  fi

  if type -P screen >/dev/null; then
    return 0
  fi

  return 1
}

source sub "$0" "$@"
