#!/usr/bin/env bash

function profile {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  source app_strict
  source app_shortcuts
  source app_debug

  source home_terminal
  source home_cache
}

profile
