#!/usr/bin/env bash

function profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  source app_strict
  source app_shortcuts
  source app_debug

  export PKG_HOME="$shome"

  require pkgsrc
  require phoenix
  require jq
  require cue junas defn
  require runmany deploy boxcar

  source home_iterm

  export GIT_SSH="$(which cache-git 2>&- || echo ssh)"
}

profile
