#!/usr/bin/env bash

function profile {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  PATH="$shome/bin:$shome/exec:$PATH"

  source app_strict
  source app_shortcuts
  source app_debug

  export PKG_HOME="$shome"

  require pkgsrc
  require python ansible aws gcloud letsencrypt
  require erlang elixir phoenix
  require ruby rocco tugboat
  require node dnsimple
  require go hub
  require jq
  require cue junas defn
  require runmany deploy boxcar
  require scripts-to-rule-them-all
  require vagrant #packer

  source home_iterm
}

if ! profile; then
  true
fi

set +efu
