#!/usr/bin/env bash

function configure_cue {
  : ${SHLVL_INITIAL:=0}

  function guess_scheme {
    case "${TERM_PROGRAM:-}" in
      Apple_Terminal)
        echo slight
        ;;
      *)
        echo "${CUE_SCHEME:-${ITERM_PROFILE:-sdark}}"
        ;;
    esac
  }

  : ${CUE_SCHEME:="$(cat ~/.cue-scheme 2>&- || true)"}
  export CUE_SCHEME
  case "$(guess_scheme)" in
    slight) slight || true ;;
    *)      sdark  || true ;;
  esac
}

function home_rc {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  set +efux

  pushd "${BLOCK_PATH}/block" > /dev/null
  source script/profile
  require
  popd > /dev/null

  source home_terminal

  if tty >/dev/null 2>&1; then
    pushd "${BLOCK_PATH}/cue" > /dev/null
    require
    popd > /dev/null
    configure_cue
  fi

  alias bl='block'

  if [[ -e "$shome/exec/home_secret" ]]; then
    source home_secret
  fi
}

home_rc
