#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    screen)
      shift
      screen -S runit -d -m "$shome/script/server" "$@"
      sleep 1
      while ! screen -S runit -X status; do
        echo "detaching..." 1>&2
        sleep 1
      done
      ;;
    default)
      exec "$BLOCK_PATH/runit/script/server" "$@"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"

