#!/usr/bin/env bash

function home_update {
  local shome="${_defn_home_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  block compile service
}

home_update "$@"
