#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile service
  sudo ifconfig lo0 alias 172.28.128.250
}

main "$@"
